name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:

  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v2
        - run: echo "$FLY_API_TOKEN"
        - run: unzip .fly/.fly_ 
        - run: .fly/flyctl.exe deploy --depot
        - run: .fly/flyctl.exe machines run --build-depot .